server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_reservation
    username: springstudent
    password: springstudent
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    banner-mode: off